# Generated by Django 4.0.1 on 2023-01-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestentry',
            name='CardNumber',
            field=models.CharField(max_length=200, null=True, verbose_name='Card Number'),
        ),
    ]
