# Generated by Django 4.0.1 on 2023-01-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_guestentry_created_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Relation',
            field=models.CharField(choices=[('1', 'Own'), ('2', 'Spouse'), ('3', 'Husband'), ('4', 'Son'), ('5', 'Daughter'), ('6', 'Brother'), ('7', 'Sister'), ('8', 'Father'), ('9', 'Mother'), ('10', 'Friend'), ('11', 'Other')], default='1', max_length=6, null=True, verbose_name='Relation'),
        ),
    ]
